### ISSUE TITLE
'[(8)75(")75(89<9#8-6)(")75(89-)] is not an array'

### ISSUE THREAD

**Issue by asimshahzad78** [bubibubi/ExtractTablesFromPdf#10]
Hi

when i tried to read a PDF file. program throws this exception. this is only with one pdf. other pdf files red successfully.

'[(8)75(")75(89<9#8-6)(")75(89-)] is not an array'

Please help me out.

regards

**Comment by bubibubi** [comment]
Could you share the pdf?

**Comment by asimshahzad78** [comment]
Before sharing, it is requested that the file is a bank statement and you
have to maintain its confidentiality.

**Comment by asimshahzad78** [comment]
My email address is ***@***.***  plz send me a blank email.
So i will share my pdf in ur personal email.

**Comment by bubibubi** [comment]
I can't see your email address.

**Comment by asimshahzad78** [comment]
it is asimshahzad78  attherate  gmail dot com
