### ISSUE TITLE
Hello from Daniel Everest

### ISSUE THREAD

**Issue by rainbowunicorn18** [bubibubi/ExtractTablesFromPdf#11]
Hi, I am Daniel Everest, experienced developer.
I saw your issues and I am sure I can fix these bugs.
Please keep in contact with me and let's discuss more details about your project.
Thank you.

https://github.com/danieleverest

**Comment by bubibubi** [comment]
Feel free to fix it and insert a pull request

**Comment by bubibubi** [comment]
-

**Comment by rainbowunicorn18** [comment]
Okay

**Comment by rainbowunicorn18** [comment]
How much can I get paid?
I will fix all errors within this week.
What are your expectations about the deadline and budget of your project?
