### ISSUE TITLE
Numbers and Symbols Not Extracted

### ISSUE THREAD

**Issue by sarathi125** [bubibubi/ExtractTablesFromPdf#3]
Hi,

I have tried with the example.pdf, it works fine with that file.
But when I am trying to do the same extraction with my own PDF file, the numbers and Symbols are not extracted correctly.

Please advise me if I need to do any changes from my end.

Thanks.

**Comment by bubibubi** [comment]
Hi,
probably is a code page issue.
You need to debug the library with your pdf model and adapt the library according to it.
