### ISSUE TITLE
Problema TJ su riga successiva

### ISSUE THREAD

**Issue by giocaputo** [bubibubi/ExtractTablesFromPdf#4]
Stavo valutando la libreria con un file pdf.

Può capitare che TJ sia presente su riga successiva.
Non so se è normale ma è quello che succede nel mio file e quindi mi salta un valore dalla tabella.
Consigli?

BT
0 0 0 rg
569.85 -943.803906 Td
/R22 8 Tf
[(45.127,62)] 
TJ
ET
BT
0 0 0 rg
653.9 -943.803906 Td
/R22 8 Tf
[(8.950,07)]TJ
ET
BT

**Comment by giocaputo** [comment]
Modificato in questo modo, ma secondo te è normale?
E' normale che ci siano cosi diversità?

Grazie


    public class Statement
    {
        public static string GetNextStatement(string content, ref int i)
        {
            string statement = "";
            bool readingStatement = false;

            if (i >= content.Length)
                return null;

            while (i < content.Length)
            {
                if (content[i] == ' ')
                {
                    if (readingStatement)
                    {
                        i++;
                        return statement;
                    }

                    statement += " ";
                    i++;
                }
                else if (content[i] == '\n')
                {
                    i++;
                    if (content[i]=='T' && content[i+1] == 'J')
                    {
                        i=i+2;
                        statement += "TJ";
                    }
                    else
                        return statement;
                }

**Comment by bubibubi** [comment]
It's quite normal.
I started this project to read a particular pdf file.
I will insert the fixes you suggested but when you'll find a configuration that work for your pdf you can freeze it until it works.

**Comment by giocaputo** [comment]
This is the right content. I hope to generate a pull request, if do you like..

   else if (content[i] == '\n')
                {
                    i++;
                    if (i+1 <=content.Length && content[i]=='T' && content[i+1] == 'J')
                    {
                        i=i+2;
                        statement += "TJ";
                    }
                    else
                        return statement;
                }

**Comment by bubibubi** [comment]
The code it's ok.
I copy paste it.
Thanks!!!!

**Comment by bubibubi** [comment]
Looking at the code I've seen that \n must be considered as a space in every situation.
Considering \n as a space, solved other issues that I've seen during these years.
